### ISSUE TITLE
[EPIC] Listagem de países

### ISSUE THREAD

**Issue by laridtm** [involvestecnologia/mnc-ios-movies#115]
## Descrição

- [x] Na tela deverá ter uma lista com o nome de todos os países. Clicando no nome do país deverá direcionar para a segunda tela com as informações daquele país.

- [x] Criar estrutura básica da arquitetura VIP.

- [x] Acima da lista, deverá ter um campo de pesquisa para encontrar um país específico.

- [x] O app deverá receber os nomes e dados dos países de uma API.

- [x] O app deve gravar em um banco todos os dados utilizados.

Issue relacionada: https://github.com/involvestecnologia/mnc-ios-movies/issues/113
