### ISSUE TITLE
[EPIC] - Detalhes de Filme

### ISSUE THREAD

**Issue by laridtm** [involvestecnologia/mnc-ios-movies#85]
## Descrição

A segunda tela da aplicação, será composta com as informações sobre o filme, em formato de campo de texto e algumas labels. Conforme essa imagem:

![Screen Shot 2020-02-20 at 14 11 46](https://user-images.githubusercontent.com/55598696/74960344-ef45c080-53ea-11ea-8201-172a8b5051f8.png)

Link para o Zeplin: https://zpl.io/blEZX75

- [x] Botão voltar tela [#79] 
- [x] Colocar a imagem e o plano de fundo [#80]
- [x] Nome do filme e avaliação [#82]
- [x] Botão trailer [#83]
- [x] Resumo do filme [#84]
- [x] Ano e duração e filme [#90]
- [x] Qualidade do filme [#81]
- [ ] Marcador [#78]
